GET http://localhost/api/posts

###

// within: (0.045, 0.045), (-0.045, -0.045), (0.035, -0.035), (-0.035, 0.035)

POST http://localhost/api/posts
Content-Type: application/json

{
    "message": "Hello, world!",
    "location": {
        "coordinates": [
            -0.045,
            -0.045
        ]
    }
}

###

GET http://localhost/api/posts/0/0/80000000000

###

DELETE http://localhost/api/posts/nuke