GET http://localhost:3000/api/posts

###

// within: (0.045, 0.045), (-0.045, -0.045), (0.035, -0.035), (-0.035, 0.035)

POST http://localhost/api/posts
Content-Type: application/json

{
    "message": "Hello, world!",
    "location": {
        "coordinates": [
            181,
            90
        ]
    }
}

###

GET http://localhost/api/posts/0/0/6

###

PUT http://localhost/api/posts/64e6473b09d158257296fc6a/like

###

DELETE http://localhost:3000/api/posts/64e7777d7299a6f95e37a999/

###

DELETE http://localhost:3000/api/posts/nuke